### ISSUE TITLE
Crash on Linux

### ISSUE THREAD

**Issue by qubodup** [ducakar/openzone#3]
Hello,

Unfortunately I can't run the future most popular Linux game. I hear a short beep and it crashes.

~/.config/openzone/client.log: http://codepad.org/XG9biNSq

I did the `mkdir build && cd build && cmake .. && make` steps and in that case run.sh doesn't work. The location of the binary ends up being `./build/src/tools/openzone`

My glxinfo: http://codepad.org/wLMxqe3M

**Comment by ducakar** [comment]
Most game data is not included in the source tree, you must get it separately. Best to download and run the lastest binary release https://github.com/ducakar/openzone/releases/tag/v0.3.90. You can also try to combine the game data from the binary release with the latest source. It might work, but certainly with some issues and warnings (beeps).

I'll add a submodule with game data to fix these issues soon.

**Comment by qubodup** [comment]
Thanks, I didn't notice the releases. No problems running on my system: http://youtu.be/Kj6710EmpOA & http://youtu.be/9dIqOPQHRdw

**Comment by ducakar** [comment]
Set "lingua" in ~/.config/openzone/client.json to "en" for English. This release was meant for Slovene public and I hard-coded language detection to Slovene.

**Comment by qubodup** [comment]
Thanks!
